export {default as Posts} from "./Posts";
export {default as Login} from "./Login";
export {default as Register} from "./Register";
export {default as PostDetail} from "./PostDetail";
export {default as Profile} from "./Profile";
export {default as Submit} from "./Submit";
export {default as Messages} from "./Messages"
export {default as MyMessages} from "./MyMessages"
export {default as Search} from "./Search"
export {default as EditPost} from "./EditPost";
export {default as Header} from "./Header";
export {default as Sidebar} from "./Sidebar";
export {default as PostItems} from "./PostItems";